kind: Service
apiVersion: v1
metadata:
  name: gcp2prom
  namespace: default
  labels:
    app: gcp2prom
spec:
  type: ClusterIP
  selector:
    app: gcp2prom
  ports:
    - name: prom
      protocol: TCP
      targetPort: promscrape
      port: 9000
